TeamSodam/sodam-client

- src/hooks/useMap.tsx
#40
(새로고침하지 않는) 클라이언트사이드에서 라우팅되면서 지도가 렌더링 안되는 경우는 없는지! 봐주세요!
0.5h
ㅋ 생각보다 금방돼서 놀람
> [#40] [BUG] E#6-S#1 소품샵 상세 지도 렌더링 이슈 

- mock-api.json
- src/components/review/OtherReviewCard.tsx
- src/components/review/ReviewDetailCard.tsx
- src/pages/review/detail/[reviewId].tsx
리뷰 상세페이지 좋아요, 스크랩 버튼 기능을 구현했어요
- 버튼을 클릭할 때 숫자가 바뀌는지
- 99보다 큰 숫자인 상황에서 버튼을 클릭했을 때 99+가 뜨는지
- 이 밖에 예외 상황에서 잘 작동하는지
확인해주시면 너무 좋을 것 같습니당!
1hours
> [#47] [FEATURE] E#4-S#2 좋아요/스크랩 기능

- src/pages/shop/collect.tsx
저장한 소품샵 페이지를 구현하였습니다.
저장한 소품샵 데이터가 아직 없어 randomShopList 데이터를 사용하였습니다.
20분
없습니다!
> [#62] [FEATURE] E#7-S#3 저장한 소품샵 페이지 구현

- src/types/review.ts
- src/types/shop.ts
API 명세에 맞게 타입을 몇개 더 정의했습니다.
Response에 맞게 딱딱 만들어놨어요
명세와 다른 부분 은 ... 없을겁니다
20m
> [#63] [FEATURE] E#8-S#3 API Req/Res 타입 정의

- src/components/common/Navbar/GlobalNav.tsx
- src/pages/shop/collectEmpty.tsx
navbar 라우팅에 따른 CSS 적용이 제대로 되도록 수정하였습니다.
onClickMenu 함수에 있는 내용 조금 더 효율적으로 쓸 수 있는 방법이 있다면.. 말씀부탁드립니다....!!!
0.5 hours
라우팅할 주소와 조건을 주고 싶은 주소가 달라서 헷갈렸어요..!!
> bug: :bug: Navbar 라우팅 수정 #64

- src/components/common/ShopCard.tsx
- src/features/shops/shopApi.ts
- src/pages/shop/collect.tsx
- src/types/api.ts
- src/types/shop.ts
저장한 소품샵 API를 연결하였습니다.
잘 붙였어요!
3h...삽질 2.5h...
쿼리의 response타입을 지정하는데 예상했던 값은 axios response 타입으로 서버에서 주는 데이터가 wrapping이 되어있을 거라고 예상을 했다. 그런데 알고보니 이미 wrapping을 벗기고 반환을 하는 거여서 삽질을 조금 했다. 하지만 많이 알아가는 과정이었다....!
> [#71] [FEATURE] E#9-S#3 저장한 소품샵 API 연결

- mock-api.json
- next.config.js
- src/components/common/ReviewCard.tsx
- src/components/review/OtherReviewCard.tsx
- src/features/reviews/reviewApi.ts
- src/pages/index.tsx
- src/pages/review/detail/[reviewId].tsx
- src/pages/shop/detail/[id].tsx
- src/types/review.ts
오늘의 리뷰 API를 연결했습니다.
리뷰 클릭 시 리뷰상세로 이동합니다.
image가 배열로 오지 않는 부분이 있어서 우선 `typeof image === 'string'` 조건문을 통해 처리해주었습니다
1h
ㅠ
> [#75] [FEATURE] E#9-S#4, E#10-S#1 오늘의 리뷰 API 연결

- src/components/MapSidebar/ShopElement.tsx
- src/components/MapSidebar/index.tsx
- src/features/shops/shopApi.ts
- src/pages/map/[areaId].tsx
- src/types/shop.ts
지역별 소품샵 api 연결 했습니다.
연결 하면서 오류나는 부분 다 수정해서 붙였습니다.
0.5h
없었습니다!
> [#78] [FEATURE] E#9-S#2 지역별 소품샵 API 연결

- src/components/MapSidebar/ShopElement.tsx
- src/components/review/ShopSearch.tsx
- src/components/review/ShopSearchList.tsx
- src/features/shops/shopApi.ts
소품샵 검색 api를 구현하였습니다.
리뷰 상세 페이지 컴포넌트 조립하실때 검색 api는 연결 안 하셔도 됩니다!
0.5h
없습니다!
> [#80] [FEATURE] E#9-S#6 소품샵 검색 API 연결

- next.config.js
- src/features/shops/shopApi.ts
- src/pages/index.tsx
카테고리별 소품샵 api를 연결했습니다.
type을 query로 넘기는 과정에서 params:{type} 형식으로 보내지 않으면 데이터가 불러와 지지 않았습니다.. 뭔가 한국어 encoding 문제라고 추측하긴 했습니다!..
2h... 삽질 1.5h....
삽질과정...
> [#85] [FEATURE] E#9-S#7 카테고리별 소품샵 API 연결

- src/features/reviews/reviewApi.ts
- src/pages/review/my/scrap.tsx
- src/types/review.ts
내가 스크랩한 리뷰 api 연결 했습니다.
잘 붙였어요!
0.5h
없습니다.
> [#84] [FEATURE] E#10-S#5 내가 스크랩한 리뷰 API 연결

- src/components/common/ReviewCard.tsx
- src/features/reviews/reviewApi.ts
- src/features/shops/shopApi.ts
- src/pages/review/my/write.tsx
- src/types/review.ts
- src/utils/parseDate.ts
내가 작성한 리뷰 페이지 api를 연결 하였습니다.
받아 온 date 객체를 parsing하여 review card 컴포넌트에서 보여지도록 구현하였습니다.
+ `src/utils/parseDate.ts` 에 date를 parsing 하여 `0000년 00월 00일` 스트링으로 반환하는 함수를 export 하여 사용할 수 있도록 구현해 두었습니다. 다른 컴포넌트에서도 사용하시면 되겠습니다!
+ `review.ts` 에서 date의 모든 타입을 string으로 변경 해 두었습니다. 서버에서 string 으로 들어오더라구요!
1h
없습니다!
> [#82] [FEATURE] E#10-S#4 내가 작성한 리뷰 API 연결

- next.config.js
- src/features/reviews/reviewApi.ts
- src/types/review.ts
```typescript
export interface ReviewWriteRequest {
shopId: number;
shopName: string;
image: File[];
item: Item[];
content: string;
tag: string[];
}
```
위의 인터페이스에 해당하는 데이터를 인자로 받아 리뷰를 등록하는 훅을 생성했습니다.
```typescript
const initList: File[] = [];
const parsedImageList = reviewImageList.reduce((acc, cur) => {
if (cur.file !== null) return [...acc, cur.file];
return acc;
}, initList);
const dummy: ReviewWriteRequest = {
shopId: 158,
shopName: '선호도의',
image: parsedImageList,
content: '테스트입ddddddddddddddddddddddddddddddddddd니다',
item: [
{
itemName: '인테리어소품',
price: '2,900원 이하',
},
],
tag: ['1', '2'],
};
const [postReview] = usePostReviewMutation();
await postReview(someThing)
```
위의 더미데이터를 사용해서 `/review/write` 페이지에서 정상작동하는 것 확인했습니다~!
postReview 함수가 리뷰 업로드를 요청하는 함수입니다
endpoints에서 `build.query`가 아닌 …
> [#87] [FEATURE] E#10-S#6 리뷰작성 mutation API

- src/components/ShopDetail/DetailImageGrid/index.tsx
- src/components/review/ReviewDetailCard.tsx
- src/features/reviews/reviewApi.ts
- src/pages/review/detail/[reviewId].tsx
- src/pages/shop/detail/[id].tsx
- src/types/review.ts
- src/types/shop.ts
소품샵상세페이지에서 리뷰 슬라이더에 들어가는 해당소품샵의 리뷰리스트를 불러오는 API를 연결했어요.
다른 API와 다르게 
```
{
reviewCount: number;
data: Response;
}
```
형태로 한번 더 래핑되어있습니당
0.5h
딱히 없었습니다
> [#92] [FEATURE] E#10-S#2 소품샵 상세의 리뷰 API 연결

- src/constants/dropdownOptionList.ts
- src/pages/review/detail/[reviewId].tsx
리뷰 상세 페이지의 해당 소품샵의 다른 리뷰 필터를 구현하였습니다.
혁진님이 작성한 코드를 조금 변경한 부분이 있는데 괜찮은지 봐주세요.
0.5h
없습니다!
> [#101] [FEATURE] E#8-S#2 리뷰상세 페이지 필터 구현

- src/hooks/useMap.tsx
- src/map/utils/display.ts
- src/map/utils/search.ts
#96 에 버그리포트 작성했습니다!
소품샵 지도에서 마포구로 이동했을 때 혹은 다른 행정구로 갔을 때 에러가 발생하는지 체크해주세요!
마포구에서 에러발생한 것 확인해서 이 이슈를 생성했는데 아마 다른 곳에서도 잘 동작할 것 같습니다
10m
코드가 점점 ... 구려지는 것 같다 ㅠ
> [#96] [BUG] 지도 좌표 검색 실패하는 이슈

- src/components/common/MoreFilter.tsx
- src/features/shops/shopApi.ts
- src/pages/index.tsx
더보기 필터를 구현했습니다~~_
useLazyQuery를 사용해서 필터에 따른 온클릭함수를 구현했어요!
0.5h
`문구·팬시`를 `문구팬시`로 파싱해야하는 것을 잊어서 살짝 헷갈렸습니당
> [#102] [FEATURE] E#8-S#2 메인페이지 카테고리 더보기 필터

- src/components/review/ReviewDetailCard.tsx
리뷰 상세페이지 이미지 API 연결
우왕 나도 API 붙여봤다~
0.5hours
나도 성장한다~
> [#000] [FEATURE] E#10-S#3 리뷰 상세페이지 이미지 API 연결

- src/constants/dropdownOptionList.ts
- src/pages/shop/detail/[id].tsx
소품샵 상세페이지 리뷰 필터링 연결했습니다
찐썬과 함께여서 너무 좋았어요
0.5 hour 
SHOP_ID가 왜 안 넘어왔는지 정말 의문이었어요... 핳 권혁진 전희선 최고~
> [#109] [FEATURE] E#9-S#9 소품샵 상세페이지 리뷰 필터링 API 연결

- src/components/Auth/SignupForm.tsx
- src/components/Auth/SignupOption.tsx
- src/components/Auth/ThemeSelector.tsx
- src/components/common/PersonalInfoInput.tsx
- src/hooks/useInfoType.ts
- src/hooks/useInput.ts
- src/pages/auth/join.tsx
- src/types/user.ts
회원가입 뷰 구현했습니다. 아직 디자인 확정 전이라 나오는대로 수정할 예정입니다~ 기능 구현을 위해서 껍데기만 대충 만들어 놨어요! 색상도 안나왔길래 제맘대로 때려박았습니다~ 수정예정~
반복되는 컴포넌트를 어케 해야할지몰라서 일단 짜긴했는데 조잡한 느낌이 들어요..
8h..?
그냥... 마니어려워따~...
> [#115] E#11-S#5 회원가입 뷰 구현 (확정 전) 

- src/components/MapSidebar/ShopElement.tsx
- src/components/common/ReviewCard.tsx
- src/components/common/ShopCard.tsx
- src/map/overlays/tooltip.tsx
- src/pages/shop/detail/[id].tsx
- src/types/review.ts
- src/types/shop.ts
- src/utils/loadImageSafely.ts
- src/utils/parseCategorySafely.ts
* Closes #138 
이미지와 카테고리가 null로 넘어올 때의 예외 처리
0.5h
저번에 봤던 에러였는데 그 때 왜 미리 예외처리를 하지 않았을까 하는 고민..
> [#138] [BUG] E#X-S#X image 예외 처리

- src/components/common/MainSlider.tsx
- src/components/common/ReviewCard.tsx
- src/components/common/ShopCard.tsx
- src/components/common/ShopCardRank.tsx
- src/pages/index.tsx
- 소품샵 카드 / 리뷰 카드 데스크탑 반응형
- 이미지 슬라이더 데스크탑 반응형
- `next/image` 고정값 삭제
- 딱히 없음,,,ㅎㅎ 너무 늦어서 죄송함다
- 약 2시간
- 이미지 슬라이더가 맘대로 안 돼서 빡쳤지만 최대한 디자인이랑 비슷하게 구현했습니당... 모바일도 얼른 할게요! 아 그리고 아직 메인페이지 데스크탑 반응형 적용 안 된듯 하니 카드 반응형 끝나면 제가 작업할게염
> [#124][FEATURE] E#12-S#3 데스크탑 카드 반응형

- src/components/common/Navbar/GlobalNav/Mobile.tsx
- src/features/users/userApi.ts
- src/pages/mypage.tsx
mypage에서 받아오는 theme type을 수정했습니당
> fix: mypage userTheme type

- src/components/Auth/SignupForm.tsx
- src/components/Auth/SignupOption.tsx
- src/components/common/PersonalInfoInput.tsx
- src/components/review/ReviewDetailCard.tsx
- src/constants/joinInfoList.ts
- src/features/auth/authApi.ts
- src/hooks/useInput.ts
- src/pages/auth/join.tsx
- src/types/auth.ts
* Closes #146
* Closes #144 
이메일 인증 (중복확인, 인증번호 메일로 전송, 인증번호 코드 받아서 일치 확인 후 인증완료) 과정 api연결하여 구현했습니다.
로컬 스토리지에 인증 코드를 받아서 저장해두고 프론트 단에서 비교 후에 일치하는지 확인 후 일치하면 스토리지에서 다시 값을 삭제해주었습니다.
2시간?
딱히 없엇어욧 근데 다른 예외가 있을런지 딱히 생각이 안나네욤
> [#146] [FEATURE] E#11-S#6 이메일 확인 api 연결

- src/components/LocalShopInfo/ShopList.tsx
- src/components/ShopDetail/DetailInfo/index.tsx
- src/components/common/Navbar/GlobalNav/index.tsx
- src/components/common/WriteReviewLink.tsx
- src/components/review/ReviewDetailCard.tsx
- src/pages/auth/login.tsx
- src/pages/review/my/write.tsx
- src/pages/shop/detail/[id].tsx
* Closes #174 
로그인하지 않은 유저에 대해서 인증이 필요한 작업 요청 시 로그인하도록 필터링했어요!
login페이지에 query를 붙여 이전 페이지를 표시하도록 했는데 .. 음 괜찮은 방법인지 모르겠네요
3h정도!
반복되는 구조가 많은 것 같은데 이후에 좀 더 고민해볼게요 ! ... to be continued...
> [#174] [FEATURE] E#11-S#11 미인증유저 필터링 

- next.config.js
- src/components/BannerList/index.tsx
- src/components/Mypage/UserInfoInput.tsx
- src/components/Mypage/UserInfoWrap.tsx
- src/components/Mypage/UserTheme.tsx
- src/components/Mypage/UserThemeItem.tsx
- src/components/common/Layout.tsx
- src/components/common/Navbar/GlobalNav/Desktop.tsx
- src/pages/mypage.tsx
10px 미만 버튼 크기를 수정했습니다
기기 화면 크기가 웹페이지보다 큰 경우, 푸터를 화면 하단에 고정시켰습니다.
그 외 짜잘한 작업...
> [#172][FEATURE] E#A-S#3 버튼 크기 및 레이아웃 수정
